ShriKrishna21/finalsalesrep

lib/common_api_class.dart

api common class

---

lib/unit/circulationincharge/createstaff.dart

circulationincharge

---

lib/unit/circulationincharge/circulationinchargescreen.dart

circulation

---

android/app/src/main/AndroidManifest.xml
lib/common_api_class.dart
lib/login/loginscreen.dart
lib/modelclasses/approveagent.dart
lib/unit/segmentincharge/approveagents.dart

aprroveeeee

---

lib/agent/agentprofie.dart
lib/unit/circulationincharge/AgentDetailsScreen.dart
lib/unit/unitmanager/allcustomerforms.dart

circulationincharge/AgentDetailsScreen ,  unitmanager/allcustomerforms

 circulationincharge/AgentDetailsScreen ,  unitmanager/allcustomerforms

---

lib/unit/noofresources.dart
lib/unit/unitmanager/agentservice.dart
lib/unit/unitmanager/allcustomerforms.dart
lib/unit/unitmanager/unitmanagerscreen.dart

 unit manager

---

lib/agent/agentscreen.dart
lib/login/loginscreen.dart
lib/modelclasses/loginmodel.dart
lib/modelclasses/routefetch.dart
lib/modelclasses/routemap.dart
lib/unit/circulationincharge/assigntargetscreen.dart
lib/unit/circulationincharge/circulationinchargescreen.dart

assign  target and route screen

assign  target and route screen

---

lib/agent/historypage.dart

  historypage

---

lib/agent/agentscreen.dart
lib/regionalhead/reginoalheadscreen.dart
lib/unit/circulationincharge/circulationinchargescreen.dart
lib/unit/officestaff.dart/officestaffscreen.dart
lib/unit/segmentincharge/segmentinchargescreen.dart
lib/unit/unitmanager/unitmanagerscreen.dart

changed all the toogles

---

lib/unit/circulationincharge/assigntargetscreen.dart
lib/unit/circulationincharge/circulationinchargescreen.dart

circulation incharge

---

lib/agent/historypage.dart
lib/agent/onedayhistory.dart
lib/unit/noofresources.dart
lib/unit/officestaff.dart/viewcreatedagents.dart
lib/unit/unitmanager/allcustomerforms.dart

added searchbars and latest agents and forms will fetched at top

 added searchbars and latest agents and forms will fetched at top

---

lib/agent/agentprofie.dart
lib/agent/agentscreen.dart
lib/agent/coustmerform.dart
lib/agent/historypage.dart
lib/agent/onedayhistory.dart

added refresh feature in agent login

added refresh feature in agent login

---

android/app/build.gradle.kts
android/app/src/main/AndroidManifest.xml
lib/l10n/app_en.arb
lib/l10n/app_localization.dart
lib/l10n/app_localization_en.dart
lib/l10n/app_localization_te.dart
lib/unit/circulationincharge/assigntargetscreen.dart
lib/unit/circulationincharge/circulationinchargescreen.dart
lib/unit/circulationincharge/createstaff.dart
lib/unit/noofresources.dart

languaage change

---

lib/agent/agentscreen.dart
lib/circulationhead/circulationhead.dart
lib/regionalhead/reginoalheadscreen.dart
lib/unit/circulationincharge/circulationinchargescreen.dart
lib/unit/officestaff.dart/officestaffscreen.dart
lib/unit/segmentincharge/segmentinchargescreen.dart
lib/unit/unitmanager/unitmanagerscreen.dart

login issue solved

---

lib/circulationhead/circulationhead.dart
lib/modelclasses/UnitWiseUsers.dart
lib/modelclasses/noofagents.dart
lib/modelclasses/unitwiseagentsmodel.dart
lib/regionalhead/reginoalheadscreen.dart
lib/unit/segmentincharge/approveagents.dart
lib/unit/segmentincharge/approvedagents.dart

fixed agents

---

lib/agent/historypage.dart
lib/unit/unitmanager/allcustomerforms.dart

image size

---

lib/agent/coustmerform.dart
lib/agent/onedayhistory.dart

customerform changes

---

pubspec.yaml

logo change in pubsec

---

lib/agent/agentprofie.dart
lib/agent/agentscreen.dart
lib/circulationhead/circulationhead.dart
lib/login/loginscreen.dart
lib/modelclasses/loginmodel.dart

upload profile

---

lib/agent/agentscreen.dart

agent screen

---

lib/agent/agentscreen.dart
lib/l10n/app_en.arb
lib/l10n/app_localization.dart
lib/l10n/app_localization_en.dart
lib/l10n/app_localization_te.dart
lib/l10n/app_te.arb

language changin in agent screen

language changin in agent screen

---

lib/agent/agentscreen.dart
lib/agent/historypage.dart
lib/unit/circulationincharge/AgentDetailsScreen.dart
lib/unit/circulationincharge/circulationinchargescreen.dart
lib/unit/circulationincharge/today_staff_attendance.dart
lib/unit/circulationincharge/total_staff_attendance.dart
lib/unit/noofresources.dart
lib/unit/segmentincharge/approveagents.dart
lib/unit/segmentincharge/approvedagents.dart

today and total attendance

---

lib/unit/circulationincharge/AgentDetailsScreen.dart
lib/unit/circulationincharge/toaday_customerforms_agent.dart
lib/unit/circulationincharge/today_staff_attendance.dart
lib/unit/circulationincharge/total_customerform_agency.dart
lib/unit/circulationincharge/total_customerforms_agent.dart
lib/unit/circulationincharge/total_staff_attendance.dart
lib/unit/today_customerforms_agencylist.dart

agentdetail screen

---

lib/circulationhead/regionheadunits.dart
lib/modelclasses/usersbyid.dart
lib/regionalhead/unittotalcustomerforms.dart

circulation Head

---

lib/agent/agentscreen.dart

agents screen

---

lib/agent/agentscreen.dart
lib/modelclasses/agencymodel.dart
lib/regionalhead/createunits.dart
lib/unit/circulationincharge/createstaff.dart

demo update

---

lib/unit/circulationincharge/circulationinchargescreen.dart

made changes in circulation incharge screen

made changes in circulation incharge screen
